[package]
name = "low-level-http-api"
version = "0.1.0"
authors = ["Chris Tramel <hello@christophertrml.com>"]
edition = "2018"

[dependencies.mio]
version = "0.6.19"

[dependencies.failure]
version = "0.1.5"